$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json

name: blue
endpoint_name: __ENDPOINT_NAME__

model: azureml:__MODEL_NAME__:__MODEL_VERSION__

environment:
  name: iris-inference-env
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
  conda_file: conda.yml

code_configuration:
  code: src
  scoring_script: score.py

instance_type: Standard_DS2_v2
instance_count: 1

data_collector:
  rolling_rate: Hour
  sampling_rate: 1.0
  collections:
    model_inputs:
      enabled: 'true'
    model_outputs:
      enabled: 'true'